[project]
name = "declusor"
version = "0.3.1"
description = "A unified, interactive CLI for remotely executing scripts, managing payloads, establishing interactive command sessions, and handling file transfers across remote environments."
readme = "README.md"
requires-python = ">=3.11,<4.0"
license = { file = "LICENSE" }
authors = [{ name = "Othon Hugo", email = "othonhugo@users.noreply.github.com" }]
keywords = [
    "security",
    "infosec",
    "cybersecurity",
    "pentesting",
    "ctf",
    "linux",
    "scripting",
    "framework",
    "post-exploitation",
    "payload-delivery",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Security",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/othonhugo/declusor/"
Repository = "https://github.com/othonhugo/declusor.git"
Issues = "https://github.com/othonhugo/declusor/issues"

[project.scripts]
declusor = "declusor.main:main"

[project.entry-points.pytest11]
declusor_testing = "declusor.testing.pytest_plugin"

[project.optional-dependencies]
testing = [
    "pytest>=8.3.4,<9",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2,<2",
    "pytest>=8.3.4,<9",
    "ruff>=0.8,<1",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13"]
build-backend = "uv_build"

[tool.uv]
default-groups = ["dev"]
link-mode = "copy"

[tool.ruff]
line-length = 150
target-version = "py311"
exclude = [
    "plugins/*/assets/*",
    "data/*",
]

[tool.ruff.lint]
ignore = ["SIM117"]
select = [
    "E",
    "F",
    "W",
    "I",
    "B",
    "UP",
    "SIM",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
python_version = "3.12"
mypy_path = "src:.:plugins/shell_socket/src:plugins/py_socket/src"
explicit_package_bases = true
exclude = ["plugins/.*/assets/.*"]
pretty = true
strict = true
disallow_any_expr = false
disallow_any_unimported = false
disallow_subclassing_any = false

[tool.pytest.ini_options]
addopts = "-ra --strict-markers --tb=short -v --import-mode=importlib"
pythonpath = ["src", ".", "plugins/shell_socket/src", "plugins/py_socket/src"]
testpaths = ["tests", "plugins"]
norecursedirs = [
    ".vscode",
    "__pycache__",
]